### PR TITLE
Fix R2 profile and errors

### PR DESCRIPTION
**Pull request by 2015aroras**
This PR fixes 2 issues:
- Using an AWS profile to authenticate doesn't work, since the profile name is passed to the S3 client rather than a session.
- `FileNotFoundError` is not being thrown when the only issue is that the object does not exists.

### CODE REVIEW

**Review by epwalsh — APPROVED** [review]
LGTM

**Comment by 2015aroras** [comment]
The tests are breaking because of the following error. I can't see the dataset on beaker myself. Any ideas @epwalsh?
`beaker.exceptions.DatasetNotFound: 'petew/cached-path-readme': Make sure you're using a valid Beaker dataset ID or the *full* name of the dataset (with the account prefix, e.g. 'username/dataset_name')`

**Comment by epwalsh** [comment]
@2015aroras yea the test fixture beaker dataset must have been deleted. I'll follow up with a separate PR to fix that.

**Comment by epwalsh** [comment]
Fixes the beaker test here: https://github.com/allenai/cached_path/pull/234

**Pull request merged**
